# Generated by Django 5.2.8 on 2025-11-20 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros_fit', '0001_initial'),
        ('core', '0007_remove_customuser_nome_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoWhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_instancia', models.CharField(help_text='Nome da instância na API', max_length=100)),
                ('token_api', models.CharField(help_text='Token de autenticação da API', max_length=255)),
                ('url_api', models.URLField(default='https://api.z-api.io/instances/', help_text='Endpoint da API')),
                ('mensagem_confirmacao', models.TextField(default='Olá {{aluno}}! Sua aula de Pilates está confirmada para amanhã às {{horario}}. Podemos contar com você?', help_text='Variáveis: {{aluno}}, {{horario}}, {{unidade}}')),
                ('ativo', models.BooleanField(default=True)),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizacao')),
            ],
        ),
        migrations.CreateModel(
            name='LogMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20)),
                ('texto', models.TextField()),
                ('tipo', models.CharField(default='CONFIRMACAO_AULA', max_length=50)),
                ('status', models.CharField(choices=[('ENVIADO', 'Enviado'), ('ERRO', 'Erro'), ('AGUARDANDO', 'Aguardando')], default='AGUARDANDO', max_length=20)),
                ('resposta_api', models.TextField(blank=True, null=True)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros_fit.aluno')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizacao')),
            ],
        ),
    ]
