# Generated by Django 5.2.8 on 2026-01-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConexaoWhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instancia', models.CharField(help_text='Nome da instância na Evolution', max_length=100)),
                ('apikey', models.CharField(help_text='ApiKey da instância', max_length=255)),
                ('url_base', models.URLField(default='https://api.sua-evolution.com')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Mensagem de Confirmação', max_length=100)),
                ('gatilho', models.CharField(choices=[('AULA_AMANHA', 'Confirmação de Aula (Dia Anterior)'), ('ANIVERSARIO', 'Aniversário do Aluno'), ('COBRANCA', 'Cobrança Manual (Botão)'), ('BOAS_VINDAS', 'Boas-vindas (Novo Aluno)')], max_length=30)),
                ('conteudo', models.TextField(help_text='Variáveis: [[aluno]], [[data]], [[horario]], [[valor]]')),
                ('horario_envio', models.TimeField(blank=True, help_text='Para mensagens automáticas', null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
