# Generated by Django 5.2.8 on 2026-01-11 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros_fit', '0001_initial'),
        ('comunicacao_fit', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conexaowhatsapp',
            name='organizacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.organizacao'),
        ),
        migrations.AddField(
            model_name='logenvio',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros_fit.aluno'),
        ),
        migrations.AddField(
            model_name='logenvio',
            name='organizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizacao'),
        ),
        migrations.AddField(
            model_name='templatemensagem',
            name='organizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizacao'),
        ),
    ]
