# Generated by Django 5.2.8 on 2026-01-11 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros_fit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoIntegracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalpass_token', models.CharField(blank=True, max_length=255, verbose_name='Token TotalPass')),
                ('totalpass_ativo', models.BooleanField(default=False)),
                ('gympass_id', models.CharField(blank=True, max_length=255, verbose_name='Gympass ID')),
                ('gympass_ativo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MacroEvolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto_padrao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENTE', 'Presente'), ('FALTA', 'Falta'), ('FALTA_JUSTIFICADA', 'Falta Justificada (Repõe)')], default='PRESENTE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField()),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('CONFIRMADA', 'Confirmada (Whats)'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='AGENDADA', max_length=20)),
                ('capacidade_maxima', models.PositiveIntegerField(default=3)),
                ('evolucao_texto', models.TextField(blank=True, verbose_name='Evolução / Prontuário')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('profissional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros_fit.profissional')),
                ('tipo_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros_fit.tiposervico', verbose_name='Tipo de Serviço')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros_fit.unidade')),
            ],
        ),
    ]
