# Generated by Django 5.2.8 on 2025-11-22 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros_fit', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField()),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('CONFIRMADA', 'Confirmada (Whats)'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='AGENDADA', max_length=20)),
                ('capacidade_maxima', models.PositiveIntegerField(default=3)),
                ('evolucao_texto', models.TextField(blank=True, verbose_name='Evolução / Prontuário')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizacao')),
                ('profissional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros_fit.profissional')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros_fit.unidade')),
            ],
        ),
        migrations.CreateModel(
            name='MacroEvolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto_padrao', models.TextField()),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizacao')),
            ],
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENTE', 'Presente'), ('FALTA', 'Falta'), ('FALTA_JUSTIFICADA', 'Falta Justificada (Repõe)')], default='PRESENTE', max_length=20)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros_fit.aluno')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='agenda_fit.aula')),
            ],
        ),
    ]
