# Generated by Django 5.2.8 on 2025-12-02 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_fit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='organizacao',
        ),
    ]
