# Generated by Django 5.2.8 on 2025-11-23 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda_fit', '0001_initial'),
        ('cadastros_fit', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='organizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizacao'),
        ),
        migrations.AddField(
            model_name='aula',
            name='profissional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros_fit.profissional'),
        ),
        migrations.AddField(
            model_name='aula',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros_fit.unidade'),
        ),
        migrations.AddField(
            model_name='macroevolucao',
            name='organizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizacao'),
        ),
        migrations.AddField(
            model_name='presenca',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros_fit.aluno'),
        ),
        migrations.AddField(
            model_name='presenca',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='agenda_fit.aula'),
        ),
    ]
