# Generated by Django 5.2.8 on 2025-12-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_fit', '0002_remove_aula_organizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoIntegracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalpass_token', models.CharField(blank=True, max_length=255, verbose_name='Token TotalPass')),
                ('totalpass_ativo', models.BooleanField(default=False)),
                ('gympass_id', models.CharField(blank=True, max_length=255, verbose_name='Gympass ID')),
                ('gympass_ativo', models.BooleanField(default=False)),
            ],
        ),
    ]
