# Generated by Django 5.2.8 on 2026-01-09 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_fit', '0003_configuracaointegracao'),
        ('cadastros_fit', '0003_tiposervico_alter_logacesso_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='tipo_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros_fit.tiposervico', verbose_name='Tipo de Serviço'),
        ),
    ]
