# Generated by Django 5.2.8 on 2025-11-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_cpf_customuser_data_expiracao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='Identificador único no código (ex: gerador-pdf)', unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='data_expiracao',
        ),
        migrations.AddField(
            model_name='customuser',
            name='produtos',
            field=models.ManyToManyField(blank=True, to='core.produto', verbose_name='Produtos Contratados'),
        ),
    ]
