# Generated by Django 5.2.8 on 2025-11-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_produto_remove_customuser_data_expiracao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='paginas_processadas',
            field=models.PositiveIntegerField(default=0, verbose_name='Páginas Analisadas'),
        ),
    ]
