# Generated by Django 5.2.8 on 2025-11-19 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_paginas_processadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_fechamento', models.DateField(auto_now_add=True, verbose_name='Data do Fechamento')),
                ('paginas_no_ciclo', models.PositiveIntegerField(verbose_name='Páginas Usadas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
