# Generated by Django 5.2.8 on 2025-11-22 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Catraca Entrada', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('token_api', models.CharField(help_text='Token para a catraca se autenticar', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('endereco', models.TextField(blank=True)),
                ('anamnese', models.JSONField(blank=True, default=dict, verbose_name='Ficha de Saúde')),
                ('foto_rosto', models.ImageField(blank=True, null=True, upload_to='alunos/fotos/')),
                ('biometria_template', models.TextField(blank=True, help_text='Hash da digital ou face para catraca', null=True)),
                ('bloqueado_catraca', models.BooleanField(default=False, help_text='Bloqueio manual ou financeiro')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizacao')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='alunos/docs/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='cadastros_fit.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='LogAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('direcao', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('status', models.CharField(choices=[('LIBERADO', 'Liberado'), ('BLOQUEADO', 'Bloqueado')], max_length=20)),
                ('motivo_bloqueio', models.CharField(blank=True, max_length=100)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros_fit.aluno')),
                ('dispositivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros_fit.dispositivoacesso')),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('crefito', models.CharField(blank=True, max_length=20, verbose_name='Registro Profissional')),
                ('cor_agenda', models.CharField(default='#007bff', help_text='Cor Hexadecimal para a agenda', max_length=7)),
                ('valor_hora_aula', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor por Aula Dada')),
                ('ativo', models.BooleanField(default=True)),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizacao')),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='core.organizacao')),
            ],
        ),
        migrations.AddField(
            model_name='dispositivoacesso',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros_fit.unidade'),
        ),
    ]
