# Generated by Django 5.2.8 on 2026-01-11 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('doc_identidade_foto', models.ImageField(blank=True, null=True, upload_to='alunos/docs_pessoais/', verbose_name='Foto RG/CNH')),
                ('cep', models.CharField(blank=True, max_length=9)),
                ('logradouro', models.CharField(blank=True, max_length=150, verbose_name='Rua/Av')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('comprovante_residencia_foto', models.ImageField(blank=True, null=True, upload_to='alunos/docs_residencia/')),
                ('anamnese', models.JSONField(blank=True, default=dict, verbose_name='Ficha de Saúde')),
                ('foto_rosto', models.ImageField(blank=True, null=True, upload_to='alunos/fotos/')),
                ('biometria_template', models.TextField(blank=True, help_text='Hash da digital ou face', null=True)),
                ('bloqueado_catraca', models.BooleanField(default=False, help_text='Bloqueio financeiro/manual')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DispositivoAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Catraca Entrada', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('token_api', models.CharField(help_text='Token de autenticação', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular/WhatsApp')),
                ('perfil', models.CharField(choices=[('ADMIN', 'Administrador'), ('INSTRUTOR', 'Instrutor / Prof.')], default='INSTRUTOR', max_length=20)),
                ('crefito', models.CharField(blank=True, max_length=20, verbose_name='Registro Profissional')),
                ('cor_agenda', models.CharField(default='#007bff', help_text='Cor Hexadecimal para a agenda', max_length=7)),
                ('valor_hora_aula', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor por Aula Dada')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=150, null=True, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cor', models.CharField(default='#802422', max_length=7)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Serviço',
                'verbose_name_plural': 'Tipos de Serviço',
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('capacidade_padrao', models.PositiveIntegerField(default=3, verbose_name='Capacidade Padrão por Aula')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='alunos/docs/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='cadastros_fit.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='LogAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('direcao', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('status', models.CharField(choices=[('LIBERADO', 'Liberado'), ('BLOQUEADO', 'Bloqueado')], max_length=20)),
                ('motivo_bloqueio', models.CharField(blank=True, max_length=100)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros_fit.aluno')),
                ('dispositivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros_fit.dispositivoacesso')),
            ],
        ),
        migrations.AddField(
            model_name='dispositivoacesso',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros_fit.unidade'),
        ),
    ]
