# Generated by Django 5.2.8 on 2026-01-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_fit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='capacidade_padrao',
            field=models.PositiveIntegerField(default=3, verbose_name='Capacidade Padrão por Aula'),
        ),
    ]
