# Generated by Django 5.2.8 on 2026-01-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_fit', '0002_profissional_bairro_profissional_cep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Serviço')),
                ('cor', models.CharField(default='#6366f1', help_text='Ex: #FF0000 para Vermelho', max_length=7, verbose_name='Cor na Agenda')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='logacesso',
            options={'verbose_name': 'Tipo de Serviço', 'verbose_name_plural': 'Tipos de Serviço'},
        ),
    ]
