# Generated by Django 5.2.8 on 2026-01-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_fit', '0003_tiposervico_alter_logacesso_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logacesso',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tiposervico',
            options={'verbose_name': 'Tipo de Serviço', 'verbose_name_plural': 'Tipos de Serviço'},
        ),
        migrations.AlterField(
            model_name='tiposervico',
            name='cor',
            field=models.CharField(default='#802422', max_length=7),
        ),
        migrations.AlterField(
            model_name='tiposervico',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
