# Generated by Django 5.2.8 on 2026-01-11 13:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros_fit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Contrato Padrão 2025', max_length=100)),
                ('texto_html', models.TextField(default='\n        <div style="text-align: center;">\n            <img src="https://via.placeholder.com/150" alt="Logo" style="max-height: 100px;">\n            <h2>CONTRATO DE PRESTAÇÃO DE SERVIÇOS</h2>\n        </div>\n        <p>Eu, {{ aluno.nome }}, CPF {{ aluno.cpf }}...</p>\n    ', help_text='Use {{aluno.nome}}, {{valor}}, {{data_inicio}} como variáveis.')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('dia_vencimento', models.PositiveIntegerField(default=10, help_text='Dia do mês para vencer o boleto/pix')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor FINAL fechado', max_digits=10)),
                ('qtde_parcelas', models.PositiveIntegerField(default=1, help_text='Em quantas vezes será gerado o financeiro?')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente Assinatura'), ('ENVIADO_EMAIL', 'Enviado p/ Assinatura (E-mail)'), ('ASSINADO_DIGITAL', 'Assinado Digitalmente (Email)'), ('ASSINADO_PRESENCIAL', 'Assinado Presencialmente (Tablet)'), ('ASSINADO_PAPEL', 'Assinado no Papel'), ('CANCELADO', 'Cancelado'), ('ENCERRADO', 'Encerrado (Fim do Prazo)')], default='PENDENTE', max_length=30)),
                ('token_assinatura', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('assinatura_imagem', models.TextField(blank=True, help_text='Imagem Base64 da assinatura', null=True)),
                ('data_assinatura', models.DateTimeField(blank=True, null=True)),
                ('ip_assinatura', models.GenericIPAddressField(blank=True, null=True)),
                ('arquivo_assinado', models.FileField(blank=True, null=True, upload_to='contratos/assinados/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='cadastros_fit.aluno')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros_fit.unidade', verbose_name='Unidade de Atendimento')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioFixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('horario', models.TimeField()),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_fixos', to='contratos_fit.contrato')),
                ('profissional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros_fit.profissional')),
            ],
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Pilates Solo 2x - Trimestral', max_length=100)),
                ('valor_mensal', models.DecimalField(decimal_places=2, help_text='Valor base mensal (sem descontos)', max_digits=10)),
                ('frequencia_semanal', models.PositiveIntegerField(default=2, help_text='Quantas vezes por semana?')),
                ('duracao_meses', models.IntegerField(choices=[(1, 'Mensal (1 Mês)'), (3, 'Trimestral (3 Meses)'), (6, 'Semestral (6 Meses)'), (12, 'Anual (12 Meses)')], help_text='1=Mensal, 3=Trimestral, etc')),
                ('ativo', models.BooleanField(default=True)),
                ('tipo_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros_fit.tiposervico', verbose_name='Tipo de Serviço')),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contratos_fit.plano'),
        ),
    ]
