# Generated by Django 5.2.8 on 2025-11-22 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros_fit', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('dia_vencimento', models.PositiveIntegerField(default=10, help_text='Dia do mês para pagamento')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('PENDENTE', 'Pendente Assinatura'), ('CANCELADO', 'Cancelado'), ('ENCERRADO', 'Encerrado (Fim do Prazo)')], default='PENDENTE', max_length=20)),
                ('arquivo_assinado', models.FileField(blank=True, null=True, upload_to='contratos/assinados/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='cadastros_fit.aluno')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros_fit.unidade', verbose_name='Unidade de Atendimento')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioFixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('horario', models.TimeField()),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_fixos', to='contratos_fit.contrato')),
                ('profissional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros_fit.profissional')),
            ],
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Pilates Solo 2x', max_length=100)),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequencia_semanal', models.PositiveIntegerField(default=2, help_text='Quantas vezes por semana?')),
                ('duracao_meses', models.PositiveIntegerField(default=12)),
                ('ativo', models.BooleanField(default=True)),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizacao')),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contratos_fit.plano'),
        ),
        migrations.CreateModel(
            name='TemplateContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Contrato Padrão 2025', max_length=100)),
                ('texto_html', models.TextField(help_text='Use {{aluno_nome}}, {{valor}}, {{data_inicio}} como variáveis.')),
                ('ativo', models.BooleanField(default=True)),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizacao')),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='template_usado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratos_fit.templatecontrato'),
        ),
    ]
