# Generated by Django 5.2.8 on 2025-12-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos_fit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='qtde_parcelas',
            field=models.PositiveIntegerField(default=1, help_text='Em quantas vezes será gerado o financeiro?'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor FINAL fechado com o aluno (pode ter desconto)', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='dia_vencimento',
            field=models.PositiveIntegerField(default=10, help_text='Dia do mês para vencer o boleto/pix'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='duracao_meses',
            field=models.PositiveIntegerField(default=12, help_text='1=Mensal, 3=Trimestral, 6=Semestral, 12=Anual'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='nome',
            field=models.CharField(help_text='Ex: Pilates Solo 2x - Trimestral', max_length=100),
        ),
        migrations.AlterField(
            model_name='plano',
            name='valor_mensal',
            field=models.DecimalField(decimal_places=2, help_text='Valor base mensal (sem descontos)', max_digits=10),
        ),
    ]
