# Generated by Django 5.2.8 on 2025-11-20 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_fit', '0001_initial'),
        ('contratos_fit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='unidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cadastros_fit.unidade', verbose_name='Unidade de Atendimento'),
            preserve_default=False,
        ),
    ]
