# Generated by Django 5.2.8 on 2025-12-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos_fit', '0002_remove_plano_organizacao_alter_plano_duracao_meses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatecontrato',
            name='texto_html',
            field=models.TextField(default='\n        <div style="text-align: center;">\n            <img src="https://via.placeholder.com/150" alt="Logo" style="max-height: 100px;">\n            <h2>CONTRATO DE PRESTAÇÃO DE SERVIÇOS</h2>\n        </div>\n        <p>Eu, {{ aluno.nome }}, CPF {{ aluno.cpf }}...</p>\n    ', help_text='Use {{aluno.nome}}, {{valor}}, {{data_inicio}} como variáveis.'),
        ),
    ]
