# Generated by Django 5.2.8 on 2026-01-09 11:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_fit', '0003_tiposervico_alter_logacesso_options'),
        ('contratos_fit', '0004_contrato_assinatura_imagem_contrato_data_assinatura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='tipo_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros_fit.tiposervico', verbose_name='Tipo de Serviço'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='token_assinatura',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
