# Generated by Django 5.2.8 on 2026-01-11 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros_fit', '0001_initial'),
        ('contratos_fit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Cofre, Nubank, Itaú', max_length=100)),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Razão Social / Nome')),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, null=True)),
                ('cnpj_cpf', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ/CPF')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('chave_pix', models.CharField(blank=True, max_length=100, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], max_length=10)),
                ('categoria_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='financeiro_fit.categoriafinanceira', verbose_name='Categoria Pai')),
            ],
            options={
                'verbose_name': 'Categoria Financeira',
                'verbose_name_plural': 'Categorias Financeiras',
                'ordering': ['tipo', 'categoria_pai__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('grupo_serie', models.UUIDField(blank=True, help_text='ID que agrupa parcelas recorrentes', null=True)),
                ('parcela_atual', models.PositiveIntegerField(default=1, help_text='1/12')),
                ('total_parcelas', models.PositiveIntegerField(default=1, help_text='12')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('PIX', 'Pix'), ('DINHEIRO', 'Dinheiro'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('BOLETO', 'Boleto'), ('TRANSFERENCIA', 'Transferência')], max_length=20, null=True)),
                ('arquivo_boleto', models.FileField(blank=True, null=True, upload_to='financeiro/boletos/', verbose_name='Boleto (PDF)')),
                ('arquivo_comprovante', models.FileField(blank=True, null=True, upload_to='financeiro/comprovantes/', verbose_name='Comprovante de Pgto')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('aluno', models.ForeignKey(blank=True, help_text='Se for Mensalidade', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros_fit.aluno')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro_fit.categoriafinanceira')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro_fit.contabancaria', verbose_name='Conta/Caixa de Saída/Entrada')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratos_fit.contrato')),
                ('fornecedor', models.ForeignKey(blank=True, help_text='Se for Despesa (Luz, Água)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro_fit.fornecedor')),
                ('profissional', models.ForeignKey(blank=True, help_text='Se for Pagamento de Salário', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros_fit.profissional')),
            ],
        ),
    ]
