# Generated by Django 5.2.8 on 2025-12-03 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_fit', '0001_initial'),
        ('financeiro_fit', '0002_alter_categoriafinanceira_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Razão Social / Nome')),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, null=True)),
                ('cnpj_cpf', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ/CPF')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('chave_pix', models.CharField(blank=True, max_length=100, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='lancamento',
            name='arquivo_boleto',
            field=models.FileField(blank=True, null=True, upload_to='financeiro/boletos/', verbose_name='Boleto (PDF)'),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='arquivo_comprovante',
            field=models.FileField(blank=True, null=True, upload_to='financeiro/comprovantes/', verbose_name='Comprovante de Pgto'),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='grupo_serie',
            field=models.UUIDField(blank=True, help_text='ID que agrupa parcelas recorrentes', null=True),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='parcela_atual',
            field=models.PositiveIntegerField(default=1, help_text='1/12'),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='profissional',
            field=models.ForeignKey(blank=True, help_text='Se for Pagamento de Salário', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros_fit.profissional'),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='total_parcelas',
            field=models.PositiveIntegerField(default=1, help_text='12'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='aluno',
            field=models.ForeignKey(blank=True, help_text='Se for Mensalidade', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros_fit.aluno'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro_fit.contabancaria', verbose_name='Conta/Caixa de Saída/Entrada'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('PIX', 'Pix'), ('DINHEIRO', 'Dinheiro'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('BOLETO', 'Boleto'), ('TRANSFERENCIA', 'Transferência')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='fornecedor',
            field=models.ForeignKey(blank=True, help_text='Se for Despesa (Luz, Água)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro_fit.fornecedor'),
        ),
    ]
