# Generated by Django 5.2.8 on 2026-01-11 13:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros_fit', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermoTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('USO_IMAGEM', 'Uso de Imagem'), ('RESPONSABILIDADE', 'Termo de Responsabilidade'), ('LGPD', 'Consentimento LGPD')], default='USO_IMAGEM', max_length=30)),
                ('texto_html', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizacao')),
            ],
        ),
        migrations.CreateModel(
            name='TermoAssinado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_assinatura', models.DateTimeField(blank=True, null=True)),
                ('assinatura_imagem', models.TextField(blank=True, null=True)),
                ('ip_assinatura', models.GenericIPAddressField(blank=True, null=True)),
                ('token_assinatura', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termos', to='cadastros_fit.aluno')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='termos_fit.termotemplate')),
            ],
        ),
    ]
